---
name: Component tests

on:
  pull_request:
    branches:
      - main

jobs:
  test-ct:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-2019
          - windows-2022
          - macos-11
          - macos-12
          - macos-13
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies (Linux)
        run: sudo apt-get update && sudo apt-get install libpulse-dev pulseaudio
        if: startsWith(matrix.os, 'ubuntu')

      - name: Start sound server (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: pulseaudio -D --start

      - name: Configure pulseaudio (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt install -y pipewire pipewire-pulse pipewire-media-session
          sudo touch /usr/share/pipewire/media-session.d/with-pulseaudio
          systemctl --user restart pipewire-session-manager

      - name: Install virtual audio devices (Windows)
        if: startsWith(matrix.os, 'windows')
        run: git clone https://github.com/LABSN/sound-ci-helpers && powershell sound-ci-helpers/windows/setup_sound.ps1

      - name: Allow microphone access to all apps (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: pwsh
        run: |
          New-Item -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppPrivacy\"
          New-ItemProperty -Path "HKLM:\SOFTWARE\policies\microsoft\windows\appprivacy" -Name "LetAppsAccessMicrophone" -Value "0x00000001" -PropertyType "dword"

      - name: Install virtual audio devices (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install switchaudio-osx
          brew install blackhole-2ch
          SwitchAudioSource -s "BlackHole 2ch" -t input
          SwitchAudioSource -s "BlackHole 2ch" -t output

      - name: Allow microphone access to all apps (macOS 14)
        if: ${{ matrix.os == 'macos-14' }}
        run: |
          sqlite3 $HOME/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT OR IGNORE INTO access VALUES ('kTCCServiceMicrophone','/usr/local/opt/runner/provisioner/provisioner',1,2,4,1,NULL,NULL,0,'UNUSED',NULL,0,1687786159,NULL,NULL,'UNUSED',1687786159);"

      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - run: npm run test-ct

      - name: Upload test results
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        if: always()
        with:
          name: test-results-${{ matrix.os }}
          path: test-results/
