---
name: Component tests

on:
  pull_request:
    branches:
      - main

jobs:
  test-devices:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - macos-12
          - macos-13
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - run: brew install blackhole-2ch switchaudio-osx
      - run: SwitchAudioSource -a
      - run: SwitchAudioSource -c
      - run: SwitchAudioSource -s 'BlackHole 2ch'
      - run: SwitchAudioSource -c
