---
name: Component tests

on:
  pull_request:
    branches:
      - main

jobs:
  test-ct:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-2019
          - windows-2022
          - macos-11
          - macos-12
          - macos-13
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - name: Create virtual audio device on Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y alsa-utils
          sudo modprobe snd-aloop

      - name: Install BlackHole (virtual audio driver) on macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install blackhole-2ch switchaudio-osx
          SwitchAudioSource -s 'BlackHole 2ch'

      # https://github.com/actions/runner-images/issues/2528#issuecomment-934857719
      - name: Install Scream (virtual audio driver) on Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          # Disable Hyper-V time sync
          # https://github.com/actions/runner-images/discussions/8105
          Set-Service -Name vmictimesync -Status stopped -StartupType disabled
          Set-ItemProperty HKLM:\SYSTEM\CurrentControlSet\services\W32Time\Parameters -Name 'Type' -Value 'NoSync'

          Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/4.0/Scream4.0.zip -OutFile Scream4.0.zip
          # Set the date to before the certificate expires
          Set-Date (Get-Date "2023-06-01 12:00:00");
          Expand-Archive -Path Scream4.0.zip -DestinationPath Scream
          Import-Certificate -FilePath Scream\Install\driver\x64\Scream.cat -CertStoreLocation Cert:\LocalMachine\TrustedPublisher
          Scream\Install\helpers\devcon-x64.exe install Scream\Install\driver\x64\Scream.inf *Scream

          # Re-enable Hyper-V time sync
          Set-ItemProperty HKLM:\SYSTEM\CurrentControlSet\services\W32Time\Parameters -Name 'Type' -Value 'NTP'
          Set-Service -Name vmictimesync -Status running -StartupType automatic

      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - run: npm run test-ct

      - name: Upload test results
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        if: always()
        with:
          name: test-results-${{ matrix.os }}-pwsh
          path: test-results/
